### PR TITLE
Feat:AuthContext-login-signup

### PR DESCRIPTION
**Pull request by LordUttam**
Added Login, Signup and Logout feature.
Test credentials:
email: test@xmail.com,
password: test1234,
Need to add cart and wishlist management through API.

### CODE REVIEW

**Review by Mohasin-Haque — COMMENTED** [review]
Your code looks good to me. You can add feature of wrong password, so whenever any user enters a wrong password it should  show an error message.

**Comment by SRUJANA-PENUGONDA13** [comment]
Signup id not working can you please verify once. Remaining all good.

**Comment by LordUttam** [comment]
> Your code looks good to me. You can add feature of wrong password, so whenever any user enters a wrong password it should show an error message.
It is there but I will add an animated alert component from CL soon.
image

**Comment by LordUttam** [comment]
> Signup id not working can you please verify once. Remaining all good.

Thanks for catching that, I have fixed it. Please check it once now :)

**Pull request merged**
